# Generated by Django 3.0.8 on 2022-05-18 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FAQs',
        ),
        migrations.DeleteModel(
            name='TopBrand',
        ),
    ]
