# Generated by Django 3.0.8 on 2022-05-18 10:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=100)),
                ('confirmed_email', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('suspended', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Newsletter Subscribers',
            },
        ),
    ]
