# Generated by Django 3.0.8 on 2022-05-18 11:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQs',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('question', models.CharField(max_length=200)),
                ('answer', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'FAQ',
            },
        ),
        migrations.CreateModel(
            name='TopBrand',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.FileField(null=True, upload_to='static/images/')),
            ],
            options={
                'verbose_name_plural': 'Home Page Top Brand',
            },
        ),
    ]
