# Generated by Django 3.0.8 on 2022-05-22 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_faqs_topbrand'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TopBrand',
        ),
    ]
