# Generated by Django 3.0.8 on 2022-05-03 01:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phones',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('brand', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('phone_image_front', models.TextField()),
                ('phone_image_back', models.TextField()),
                ('phone_image_side', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('rating', models.IntegerField()),
                ('new', models.BooleanField()),
                ('network', models.CharField(max_length=100)),
                ('body_form_factor', models.CharField(max_length=100)),
                ('body_color', models.CharField(max_length=100)),
                ('os', models.CharField(max_length=100)),
                ('ram', models.IntegerField()),
                ('storage', models.IntegerField()),
                ('display_resolution', models.CharField(max_length=100)),
                ('main_camera_resolution', models.CharField(max_length=100)),
                ('selfie_camera_resolution', models.CharField(max_length=100)),
                ('wlan', models.BooleanField()),
                ('bluetooth', models.BooleanField()),
                ('gps', models.BooleanField()),
                ('fm_radio', models.BooleanField()),
                ('battery_capacity', models.CharField(max_length=100)),
                ('battery_duration', models.CharField(max_length=100)),
                ('battery_removable', models.BooleanField()),
                ('fingerprint_sensor', models.BooleanField()),
                ('water_resistant', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Userfilter',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=100)),
                ('date_made', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('search', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('phone_image_front', models.TextField()),
                ('phone_image_back', models.TextField()),
                ('phone_image_side', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('rating', models.IntegerField()),
                ('new', models.BooleanField()),
                ('network', models.CharField(max_length=100)),
                ('body_form_factor', models.CharField(max_length=100)),
                ('body_color', models.CharField(max_length=100)),
                ('os', models.CharField(max_length=100)),
                ('ram', models.IntegerField()),
                ('storage', models.IntegerField()),
                ('display_resolution', models.CharField(max_length=100)),
                ('main_camera_resolution', models.CharField(max_length=100)),
                ('selfie_camera_resolution', models.CharField(max_length=100)),
                ('wlan', models.BooleanField()),
                ('bluetooth', models.BooleanField()),
                ('gps', models.BooleanField()),
                ('fm_radio', models.BooleanField()),
                ('battery_capacity', models.CharField(max_length=100)),
                ('battery_duration', models.CharField(max_length=100)),
                ('battery_removable', models.BooleanField()),
                ('fingerprint_sensor', models.BooleanField()),
                ('water_resistant', models.BooleanField()),
            ],
        ),
    ]
