# Generated by Django 3.0.8 on 2022-05-05 21:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('email', models.EmailField(max_length=100)),
                ('msg', models.TextField()),
                ('attended_to', models.BooleanField()),
                ('resolved', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='FAQs',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('question', models.CharField(max_length=200)),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=100)),
                ('confirmed_email', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('suspended', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(default=datetime.datetime.utcnow)),
            ],
        ),
        migrations.CreateModel(
            name='StatesInCountry',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=200, null=True)),
                ('states', models.TextField()),
                ('date_added', models.DateTimeField(default=datetime.datetime.utcnow)),
            ],
        ),
        migrations.CreateModel(
            name='TopBrand',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.FileField(null=True, upload_to='static/images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='phones',
            name='description',
        ),
        migrations.RemoveField(
            model_name='userfilter',
            name='phone_image_back',
        ),
        migrations.RemoveField(
            model_name='userfilter',
            name='phone_image_front',
        ),
        migrations.RemoveField(
            model_name='userfilter',
            name='phone_image_side',
        ),
        migrations.AlterField(
            model_name='phones',
            name='phone_image_back',
            field=models.FileField(null=True, upload_to='static/images/'),
        ),
        migrations.AlterField(
            model_name='phones',
            name='phone_image_front',
            field=models.FileField(null=True, upload_to='static/images/'),
        ),
        migrations.AlterField(
            model_name='phones',
            name='phone_image_side',
            field=models.FileField(null=True, upload_to='static/images/'),
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('phone_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Phones')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClickedTOProduct',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('click_to_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Phones')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
