# Generated by Django 3.0.8 on 2022-11-13 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phones',
            name='phone_image_back',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='phones',
            name='phone_image_front',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='phones',
            name='phone_image_side',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
