# Generated by Django 3.0.8 on 2022-05-08 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20220505_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='attended_to',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contact',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
    ]
