# Generated by Django 3.0.8 on 2022-05-10 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20220510_0504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phones',
            name='network',
            field=models.CharField(choices=[('2g', '2g'), ('3g', '3g'), ('4g', '4g'), ('5g', '5g')], max_length=100),
        ),
    ]
