# Generated by Django 3.0.8 on 2022-05-11 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20220510_0513'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': 'Contact us'},
        ),
        migrations.AlterModelOptions(
            name='faqs',
            options={'verbose_name_plural': 'FAQ'},
        ),
        migrations.AlterModelOptions(
            name='favourite',
            options={'verbose_name_plural': 'Favourites'},
        ),
        migrations.AlterModelOptions(
            name='newsletter',
            options={'verbose_name_plural': 'Newsletter Subscribers'},
        ),
        migrations.AlterModelOptions(
            name='phones',
            options={'verbose_name_plural': 'Phones'},
        ),
        migrations.AlterModelOptions(
            name='statesincountry',
            options={'verbose_name_plural': 'States and Countries'},
        ),
        migrations.AlterModelOptions(
            name='topbrand',
            options={'verbose_name_plural': 'Home Page Top Brand'},
        ),
        migrations.AlterModelOptions(
            name='userfilter',
            options={'verbose_name_plural': 'User Filter'},
        ),
        migrations.AlterField(
            model_name='userfilter',
            name='network',
            field=models.CharField(choices=[('2g', '2g'), ('3g', '3g'), ('4g', '4g'), ('5g', '5g')], max_length=100),
        ),
    ]
