# Generated by Django 3.0.8 on 2022-05-11 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20220511_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phones',
            name='battery_capacity',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='phones',
            name='battery_duration',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='phones',
            name='battery_removable',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='phones',
            name='bluetooth',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='phones',
            name='body_color',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='phones',
            name='body_form_factor',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='phones',
            name='brand',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='phones',
            name='display_resolution',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='phones',
            name='fingerprint_sensor',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='phones',
            name='fm_radio',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='phones',
            name='gps',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='phones',
            name='main_camera_resolution',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='phones',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='phones',
            name='network',
            field=models.CharField(blank=True, choices=[('2g', '2g'), ('3g', '3g'), ('4g', '4g'), ('5g', '5g')], max_length=100),
        ),
        migrations.AlterField(
            model_name='phones',
            name='new',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='phones',
            name='os',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='phones',
            name='phone_image_back',
            field=models.FileField(blank=True, null=True, upload_to='static/images/'),
        ),
        migrations.AlterField(
            model_name='phones',
            name='phone_image_front',
            field=models.FileField(blank=True, null=True, upload_to='static/images/'),
        ),
        migrations.AlterField(
            model_name='phones',
            name='phone_image_side',
            field=models.FileField(blank=True, null=True, upload_to='static/images/'),
        ),
        migrations.AlterField(
            model_name='phones',
            name='price',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='phones',
            name='ram',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='phones',
            name='rating',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='phones',
            name='selfie_camera_resolution',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='phones',
            name='storage',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='phones',
            name='water_resistant',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='phones',
            name='wlan',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='phones',
            name='year',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
