# Generated by Django 3.0.8 on 2022-05-16 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20220511_0458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phones',
            name='network',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
