# Generated by Django 3.0.8 on 2022-05-16 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20220517_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phones',
            name='ram',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='phones',
            name='rating',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='phones',
            name='storage',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
