# Generated by Django 3.0.8 on 2022-05-16 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20220517_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='phones',
            name='price_max',
            field=models.FloatField(blank=True, default=200),
            preserve_default=False,
        ),
    ]
