# Generated by Django 3.0.8 on 2022-05-17 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_phones_price_max'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phones',
            old_name='price_max',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='phones',
            name='new',
        ),
        migrations.RemoveField(
            model_name='phones',
            name='price_min',
        ),
        migrations.RemoveField(
            model_name='phones',
            name='rating',
        ),
    ]
