# Generated by Django 3.0.8 on 2022-05-17 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20220517_0104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfilter',
            old_name='date_made',
            new_name='date_added',
        ),
        migrations.RemoveField(
            model_name='userfilter',
            name='description',
        ),
        migrations.RemoveField(
            model_name='userfilter',
            name='new',
        ),
        migrations.RemoveField(
            model_name='userfilter',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='userfilter',
            name='search',
        ),
        migrations.AddField(
            model_name='userfilter',
            name='phone_image_back',
            field=models.FileField(blank=True, null=True, upload_to='static/images/'),
        ),
        migrations.AddField(
            model_name='userfilter',
            name='phone_image_front',
            field=models.FileField(blank=True, null=True, upload_to='static/images/'),
        ),
        migrations.AddField(
            model_name='userfilter',
            name='phone_image_side',
            field=models.FileField(blank=True, null=True, upload_to='static/images/'),
        ),
        migrations.AlterField(
            model_name='userfilter',
            name='battery_capacity',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userfilter',
            name='battery_duration',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userfilter',
            name='battery_removable',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='userfilter',
            name='bluetooth',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='userfilter',
            name='body_color',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userfilter',
            name='body_form_factor',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userfilter',
            name='brand',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userfilter',
            name='display_resolution',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userfilter',
            name='fingerprint_sensor',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='userfilter',
            name='fm_radio',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='userfilter',
            name='gps',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='userfilter',
            name='main_camera_resolution',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userfilter',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userfilter',
            name='network',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userfilter',
            name='os',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userfilter',
            name='price',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='userfilter',
            name='ram',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userfilter',
            name='selfie_camera_resolution',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userfilter',
            name='storage',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userfilter',
            name='water_resistant',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='userfilter',
            name='wlan',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='userfilter',
            name='year',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.DeleteModel(
            name='Favourite',
        ),
    ]
