# Generated by Django 3.0.8 on 2022-05-17 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20220517_1010'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StatesInCountry',
        ),
    ]
