# Generated by Django 3.0.8 on 2022-05-18 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_delete_statesincountry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Newsletter',
        ),
    ]
