# Generated by Django 3.0.8 on 2022-05-18 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_delete_newsletter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FAQs',
        ),
        migrations.DeleteModel(
            name='TopBrand',
        ),
    ]
