# Generated by Django 3.0.8 on 2022-05-18 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_auto_20220518_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfilter',
            name='phone_image_back',
        ),
        migrations.RemoveField(
            model_name='userfilter',
            name='phone_image_front',
        ),
        migrations.RemoveField(
            model_name='userfilter',
            name='phone_image_side',
        ),
    ]
