# Generated by Django 3.0.8 on 2022-05-18 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_auto_20220518_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfilter',
            name='price',
        ),
        migrations.AddField(
            model_name='userfilter',
            name='price_max',
            field=models.FloatField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userfilter',
            name='price_min',
            field=models.FloatField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
