# Generated by Django 3.0.8 on 2022-05-19 00:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0021_auto_20220518_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phones',
            name='battery_capacity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='phones',
            name='battery_duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='phones',
            name='battery_removable',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phones',
            name='bluetooth',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phones',
            name='body_color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='phones',
            name='body_form_factor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='phones',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='phones',
            name='date_added',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='phones',
            name='display_resolution',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='phones',
            name='fingerprint_sensor',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phones',
            name='fm_radio',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phones',
            name='gps',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phones',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='phones',
            name='main_camera_resolution',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='phones',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='phones',
            name='network',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='phones',
            name='os',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='phones',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phones',
            name='ram',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='phones',
            name='selfie_camera_resolution',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='phones',
            name='storage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='phones',
            name='water_resistant',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phones',
            name='wlan',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phones',
            name='year',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userfilter',
            name='anonymous_user_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userfilter',
            name='battery_capacity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userfilter',
            name='battery_duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userfilter',
            name='battery_removable',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userfilter',
            name='bluetooth',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userfilter',
            name='body_color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userfilter',
            name='body_form_factor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userfilter',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userfilter',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='userfilter',
            name='display_resolution',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userfilter',
            name='fingerprint_sensor',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userfilter',
            name='fm_radio',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userfilter',
            name='gps',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userfilter',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userfilter',
            name='main_camera_resolution',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userfilter',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userfilter',
            name='network',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userfilter',
            name='os',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userfilter',
            name='price_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userfilter',
            name='price_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userfilter',
            name='ram',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userfilter',
            name='selfie_camera_resolution',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userfilter',
            name='storage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userfilter',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userfilter',
            name='water_resistant',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userfilter',
            name='wlan',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userfilter',
            name='year',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
