# Generated by Django 3.0.8 on 2022-05-23 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_auto_20220522_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phones',
            name='phone_image_back',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='phones',
            name='phone_image_side',
            field=models.FileField(blank=True, null=True, upload_to='side'),
        ),
    ]
