# Generated by Django 3.0.8 on 2022-06-02 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_auto_20220523_0540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phones',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
