# Generated by Django 3.0.8 on 2022-06-04 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_auto_20220602_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfilter',
            name='price_max',
        ),
        migrations.RemoveField(
            model_name='userfilter',
            name='price_min',
        ),
        migrations.AddField(
            model_name='userfilter',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
